"""Turning your own traffic into something measurable, and refusing to pretend when it is not.

The ask this answers is reasonable and common: *my* users send *my* traffic, so measure the tiers on that
rather than on a public benchmark. The tempting implementation is to send each logged request to the best
model available, keep its answer as the correct one, and score everything else against it. That is refused
here, and the reason is a measurement in this repository rather than a principle:

  * a model's judgement of another model's output was measured at keep-precision **0.78** against a bar of
    1.00, with every error in the dangerous direction;
  * on one family the strongest tier solved **95** of 115 items while cheaper tiers solved **101**, and each
    cheaper tier solved six to nine items the strongest one failed.

An agreement-with-the-strongest benchmark would have marked the cheaper tiers *down* on exactly those items.
That is not extra noise around a true ranking. It inverts the ranking precisely where the ranking decides
something. Using an *older* strong model does not fix it either: it removes the tautology and replaces it
with a frozen ceiling, penalising every candidate on the items where it has since improved.

So two facilities ship, and they are different things with different names:

    extract_tasks()      the tasks, unconditionally. This is the part a public benchmark cannot give you.
    admissible()         the subset whose outcome something OTHER than a model decided. These may assign.
    agreement_study()    "tier X agrees with model M at version V on cohort C". Named for what it is,
                         structurally capped at provisional, and unusable as anyone's validation fold.
    disagreement_audit() the only path from an agreement study to an assignment: label the items where the
                         two disagreed, because where they agree the study says nothing about who is right.

`coverage()` reports what fraction of the log had an admissible check, because a measurement over the
checkable subset is a measurement over the checkable subset. Extrapolating it to the rest of the traffic is
the same error as the agreement benchmark wearing a different hat.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path

from tierbook.evidence import two_by_two
from tierbook.policy import EXECUTABLE_CHECK, HUMAN_LABEL, MODEL_REFERENCE

#: Ways a logged request's outcome may have been decided by something other than a model's opinion.
#: Each is a *narrow* property, and the axis a measurement over it produces is named for that property --
#: `executes`, `schema_valid` -- never for accuracy. "The command exited zero" is ground truth about the
#: exit status and is not a claim that the answer was good.
ACCEPTANCE_KINDS = {
    "exit_status": "a command was run and its exit status was recorded",
    "schema_validation": "the output was validated against a schema by something downstream",
    "parse": "the output was parsed by a consumer that would have failed on malformed input",
    "query_returned": "a generated query was executed and returned rows",
    "test_suite": "a test suite supplied with the request was run against the output",
    "downstream_accept": "a downstream system accepted or rejected the output on its own terms",
    "human_label": "a person judged this item",
}


@dataclass(frozen=True)
class LoggedTask:
    """One request out of your traffic, with whatever decided its outcome attached.

    `check` is the thing that makes a task admissible. It must have come from the log or the user side: a
    check generated by the candidate is a model's opinion wearing a shell script, and this project has the
    measurement -- tests taken from a model's own output passed on 100% of the items it had failed to solve,
    because a model that cannot fix a bug writes a test that agrees with it.
    """

    id: str
    family: str
    request: dict                       # the messages, tools and context, as they were sent
    check: dict | None = None           # {"kind": ..., "detail": ..., "origin": "log"|"user"|"candidate"}
    logged_outcome: bool | None = None  # what the check said at the time, when it was recorded
    reference_answer: dict | None = None  # a model's answer, if one was generated. Never a correct answer.
    recorded_at: str | None = None

    @property
    def admissible(self) -> bool:
        """Whether this task can support a correctness measurement at all."""
        if not self.check:
            return False
        if self.check.get("kind") not in ACCEPTANCE_KINDS:
            return False
        # The origin test is the whole test. A candidate-authored check cannot certify the candidate.
        return self.check.get("origin") in ("log", "user", "human")

    @property
    def inadmissible_reason(self) -> str | None:
        if self.admissible:
            return None
        if not self.check:
            return "no independent check was recorded, so nothing here decides whether an answer is right"
        if self.check.get("kind") not in ACCEPTANCE_KINDS:
            return f"check kind {self.check.get('kind')!r} is not one of {sorted(ACCEPTANCE_KINDS)}"
        return (f"the check originates from {self.check.get('origin')!r}; a check the candidate produced "
                "cannot certify the candidate")


def extract_tasks(path: str | Path, *, family_of=None) -> list[LoggedTask]:
    """Read a JSONL log into tasks. Ships unconditionally, because the tasks are the valuable part.

    `family_of` is a callable from a raw log line to a family name, supplied by the caller: how your traffic
    divides into families is a fact about your product that this module cannot guess, and guessing it would
    put a routing-relevant decision inside a log parser.
    """
    tasks: list[LoggedTask] = []
    for i, line in enumerate(Path(path).read_text().splitlines()):
        line = line.strip()
        if not line:
            continue
        raw = json.loads(line)
        request = raw.get("request") or {"messages": raw.get("messages") or []}
        family = (family_of(raw) if family_of else raw.get("family")) or "unclassified"
        tasks.append(LoggedTask(
            id=raw.get("id") or f"{Path(path).stem}:{i}",
            family=family,
            request=request,
            check=raw.get("check"),
            logged_outcome=raw.get("outcome"),
            reference_answer=raw.get("reference_answer"),
            recorded_at=raw.get("recorded_at") or raw.get("timestamp"),
        ))
    return tasks


def admissible(tasks: list[LoggedTask]) -> list[LoggedTask]:
    return [t for t in tasks if t.admissible]


def coverage(tasks: list[LoggedTask]) -> dict:
    """How much of the log can support a correctness claim, and why the rest cannot.

    Goes into the record's `oracle.coverage` so that a compiled decision carries the population it is about.
    A tier measured on the 12% of traffic that happened to arrive with a test suite has been measured on that
    12%; the remaining 88% is not evidence for it and not evidence against it.
    """
    reasons: dict[str, int] = {}
    ok = 0
    by_family: dict[str, dict[str, int]] = {}
    for t in tasks:
        slot = by_family.setdefault(t.family, {"considered": 0, "admissible": 0})
        slot["considered"] += 1
        if t.admissible:
            ok += 1
            slot["admissible"] += 1
        else:
            reasons[t.inadmissible_reason or "unknown"] = reasons.get(t.inadmissible_reason or "unknown", 0) + 1
    return {
        "logs_considered": len(tasks),
        "with_admissible_check": ok,
        "fraction": (ok / len(tasks)) if tasks else 0.0,
        "excluded_reasons": [f"{n} x {r}" for r, n in sorted(reasons.items(), key=lambda kv: -kv[1])],
        "by_family": by_family,
        "reading": (
            "A measurement built from these tasks is about the admissible subset only. If that subset is "
            "small or unlike the rest of your traffic, the compiled decision is about a corner of your "
            "workload -- which is worth knowing and is not a reason to widen the claim."
        ),
    }


def cohort_id(tasks: list[LoggedTask]) -> str:
    """A stable name for a set of items, so two records can be recognised as paired -- or as not paired.

    Content-addressed rather than assigned, because a hand-chosen cohort label is exactly how a held-out fold
    silently becomes the calibration fold again.
    """
    h = hashlib.sha256()
    for t in sorted(tasks, key=lambda t: t.id):
        h.update(t.id.encode() + b"\0")
    return "logs:" + h.hexdigest()[:16]


def temporal_split(tasks: list[LoggedTask], *, at: str) -> tuple[list[LoggedTask], list[LoggedTask]]:
    """Split calibration from held-out by time, which is the split that matches how a router is used.

    A random split would let the two folds share a week's worth of whatever was unusual about that week. A
    router compiled today will serve tomorrow's traffic, so the honest held-out fold is later traffic.
    """
    before = [t for t in tasks if (t.recorded_at or "") < at]
    after = [t for t in tasks if (t.recorded_at or "") >= at]
    return before, after


def acceptance_record(
    *, tier_id: str, family: str, tasks: list[LoggedTask], solved: int, bill_usd: float,
    paired_vs_reference: dict | None, checker_id: str, measured_at: str,
) -> dict:
    """The fragment of a tier record a log-derived acceptance measurement produces.

    Claim and oracle are filled in here rather than left to the caller, because the whole value of this path
    is that its output cannot be mistaken for the other path's output.
    """
    return {
        "claim": {"kind": "correctness", "metric": f"passed the request's own check ({checker_id})"},
        "oracle": {
            "kind": "executable_acceptance", "checker_id": checker_id,
            "independent_of_candidate": True, "existed_before_candidate_output": True,
            "generator": None, "coverage": coverage(tasks),
        },
        "measured_at": measured_at,
        "families": {family: {
            "suite": f"logs:{family}", "attempted": len(tasks), "solved": solved,
            "cohort": cohort_id(tasks), "bill_usd": bill_usd,
            "paired_vs_reference": paired_vs_reference,
        }},
    }


@dataclass
class AgreementStudy:
    """"Tier X produced the same answer as model M on cohort C", and nothing more than that.

    Named `reference_agreement` in the record it emits, so no compiler and no reader can mistake it for a
    correctness measurement. It is triage: it tells you where to look. Two structural consequences, both
    enforced by `tierbook.policy.evidence_class` rather than by convention:

      * it can never make an entry `assigned`;
      * it can never be anyone's validation fold -- including another agreement study's, because agreement
        about agreement compounds rather than confirms.

    The reference model is also barred from being a candidate scored against its own answers, which would be
    a tautology reported as the best result in the table.
    """

    reference_model: str
    reference_revision: str | None
    generated_at: str
    prompt_digest: str
    agreed: int = 0
    disagreed: int = 0
    items_disagreed: list[str] = field(default_factory=list)
    #: Ids of the agreed items, kept alongside `agreed` (a plain count) so `disagreement_audit` can hand a
    #: real id set -- not just a number -- to the shared `evidence.two_by_two` derivation.
    items_agreed: list[str] = field(default_factory=list)

    def observe(self, task_id: str, *, agrees: bool) -> None:
        if agrees:
            self.agreed += 1
            self.items_agreed.append(task_id)
        else:
            self.disagreed += 1
            self.items_disagreed.append(task_id)

    @property
    def rate(self) -> float | None:
        n = self.agreed + self.disagreed
        return (self.agreed / n) if n else None

    def record(self, *, tier_id: str, family: str, tasks: list[LoggedTask], bill_usd: float,
               measured_at: str) -> dict:
        n = self.agreed + self.disagreed
        axis = f"agreement@ref={self.reference_model}:{self.reference_revision or 'unpinned'}:{self.generated_at}"
        return {
            "claim": {"kind": "reference_agreement", "metric": axis},
            "oracle": {
                "kind": "model_generated_reference", "checker_id": axis,
                "independent_of_candidate": tier_id != self.reference_model,
                "existed_before_candidate_output": True,
                "generator": {"model": self.reference_model, "revision": self.reference_revision,
                              "prompt_digest": self.prompt_digest, "generated_at": self.generated_at},
                "coverage": coverage(tasks),
            },
            "measured_at": measured_at,
            "families": {family: {
                "suite": f"logs:{family}:agreement", "attempted": n, "solved": self.agreed,
                "cohort": cohort_id(tasks), "bill_usd": bill_usd, "paired_vs_reference": None,
            }},
            "warning": (
                "This is an agreement rate, not a solve rate, and tierbook will refuse to assign on it or to "
                "compare it against a solve rate under any margin. Where this tier and the reference agreed, "
                "this record contains no information about which of them was right. Audit the "
                f"{self.disagreed} disagreements to turn it into something that can route."
            ),
        }


def disagreement_audit(study: AgreementStudy, labels: dict[str, str]) -> dict:
    """Resolve an agreement study into evidence, using labels for the disagreements only.

    `labels` maps a disagreeing task id to `"candidate"`, `"reference"` or `"neither"`. This is the minimum
    hand-labelling that makes a log-derived study able to assign, and it is minimum for a structural reason:
    the agreements carry no information about who is right, so labelling them buys nothing. Typically dozens
    of items rather than thousands.

    An audit that does not cover every disagreement is refused rather than extrapolated. A partial audit
    scored as if it were complete is a smaller version of the error this whole module exists to avoid.
    """
    missing = [i for i in study.items_disagreed if i not in labels]
    if missing:
        return {
            "usable": False,
            "reason": (f"{len(missing)} of {study.disagreed} disagreements are unlabelled "
                       f"(first few: {missing[:5]}). A partial audit cannot be scaled up to the whole set: "
                       "unlabelled disagreements are exactly the items whose direction is unknown."),
        }
    candidate_right = sum(1 for i in study.items_disagreed if labels[i] == "candidate")
    reference_right = sum(1 for i in study.items_disagreed if labels[i] == "reference")
    neither = study.disagreed - candidate_right - reference_right

    # The counting arithmetic itself is `evidence.two_by_two`, shared with `evidence.paired` rather than
    # written out a second time here. What is NOT shared, and is applied right here instead, is the one
    # assumption this audit makes and does not test: every agreed item is entered into BOTH sides' `solved`
    # sets, i.e. treated as jointly correct. That is a decision about what this study's data means, made by
    # this caller before the shared function ever runs -- `two_by_two` itself assumes nothing about
    # agreement, so it cannot inherit this caller's assumption by accident the way a second hand-written copy
    # of the arithmetic could.
    agreed_ids = frozenset(study.items_agreed)
    attempted = agreed_ids | frozenset(study.items_disagreed)
    candidate_solved = agreed_ids | frozenset(i for i in study.items_disagreed if labels[i] == "candidate")
    reference_solved = agreed_ids | frozenset(i for i in study.items_disagreed if labels[i] == "reference")
    both, cand_only, ref_only, neither_check, _ = two_by_two(attempted, candidate_solved, attempted,
                                                              reference_solved)
    assert (both, cand_only, ref_only, neither_check) == (study.agreed, candidate_right, reference_right,
                                                           neither), (
        "the shared derivation disagrees with this audit's own counts; that would mean the two have drifted "
        "apart, which is the exact failure sharing this arithmetic exists to prevent"
    )

    return {
        "usable": True,
        "evidence_class": HUMAN_LABEL,
        "agreed": study.agreed,
        "disagreed": study.disagreed,
        "candidate_right": candidate_right,
        "reference_right": reference_right,
        "neither_right": neither,
        # The 2x2 an audit yields is genuinely paired and genuinely about correctness, so it is the shape
        # the compiler already consumes. `both` is approximate in one direction only: the agreements are
        # counted as jointly correct, which is the assumption the audit did not test and which the reading
        # below states rather than hides.
        "paired_vs_reference": {
            "both": both, "candidate_only": cand_only,
            "reference_only": ref_only, "neither": neither_check,
        },
        "reading": (
            "The agreed items are entered as jointly correct, which the audit did not check -- it labelled "
            "only the disagreements. Where both tiers are wrong in the same way this overstates both "
            "equally, so the paired difference is affected less than either rate. If you need the rates "
            "themselves rather than their difference, sample the agreements too."
        ),
    }
